export const linksPortal = [
  { url: "https://www.enoticiaabaetetuba.com.br/", name: "É Noticia Abaetetuba" },
  { url: "https://www.enoticiaacara.com.br/", name: "É Noticia Acará" },
  { url: "https://www.enoticiaaltamira.com.br/", name: "É Noticia Altamira" },
  { url: "https://www.enoticiaananindeua.com.br/", name: "É Noticia Ananindeua" },
  { url: "https://www.enoticiaaugustocorrea.com.br/", name: "É Noticia Augusto Corrêa" },
  { url: "https://www.enoticiaalmerin.com.br/", name: "É Noticia Almeirim" },
  { url: "https://www.enoticiaaraguaia.com.br/", name: "É Noticia Araguaia" },
  { url: "https://www.enoticiabagre.com.br/", name: "É Noticia Bagre" },
  { url: "https://www.enoticiabaixoamazonas.com.br/", name: "É Noticia Baixo Amazonas" },
  { url: "https://www.enoticiabaixotocantins.com.br/", name: "É Noticia Baixo Tocantins" },
  { url: "https://www.enoticiabarcarena.com.br/", name: "É Noticia Barcarena" },
  { url: "https://www.enoticiabelterra.com.br/", name: "É Noticia Belterra" },
  { url: "https://www.enoticiabelem.com.br/", name: "É Noticia Belém" },
  { url: "https://www.enoticiabenevides.com/", name: "É Noticia Benevides" },
  { url: "https://www.enoticiaboavistense.com.br/", name: "É Notícia Boavistense" },
  { url: "https://www.enoticiabraganca.com.br/", name: "É Noticia Bragança" },
  { url: "https://www.enoticiacaete.com.br/", name: "É Noticia Caeté" },
  { url: "https://www.enoticiacapanema.com.br/", name: "É Noticia Capanema" },
  { url: "https://www.enoticiacapim.com.br/", name: "É Noticia Capim" },
  { url: "https://www.enoticiacastanhal.com.br/", name: "É Noticia Castanhal" },
  { url: "https://www.enoticiacarajas.com.br/", name: "É Noticia Carajás" },
  { url: "https://www.enoticiacolares.com.br/", name: "É Noticia Colares" },
  { url: "https://www.enoticiaconceicaoaraguaia.com.br/", name: "É Noticia Conceição do Araguaia" },
  { url: "https://www.enoticiacuruca.com.br/", name: "É Noticia Curuçá" },
  { url: "https://www.enoticiadomeliseu.com.br/", name: "É Noticia Dom Eliseu" },
  { url: "https://www.enoticiafaro.com.br/", name: "É Noticia Faro" },
  { url: "https://www.enoticiagarrafaodonorte.com.br/", name: "É Noticia Garrafão do Norte" },
  { url: "https://www.enoticiagoianesia.com.br/", name: "É Noticia Goianésia" },
  { url: "https://www.enoticiaguajarina.com.br/", name: "É Noticia Guajarina" },
  { url: "https://www.enoticiagurupa.com.br/", name: "É Noticia Gurupá" },
  { url: "https://www.enoticiaitaituba.com.br/", name: "É Noticia Itaituba" },
  { url: "https://www.enoticiaitupiranga.com.br/", name: "É Noticia Itupiranga" },
  { url: "https://www.enoticiajuruti.com.br/", name: "É Noticia Juruti" },
  { url: "https://www.enoticialagodetucurui.com.br/", name: "É Noticia Lago de Tucuruí" },
  { url: "https://www.enoticiamagalhaesbarata.com.br/", name: "É Noticia Magalhães Barata" },
  { url: "https://www.enoticiamaraba.com.br/", name: "É Noticia Marabá" },
  { url: "https://www.enoticiamaracana.com.br/", name: "É Noticia Maracanã" },
  { url: "https://www.enoticiamarajo.com.br/", name: "É Noticia Marajó" },
  { url: "https://www.enoticiamarituba.com.br/", name: "É Noticia Marituba" },
  { url: "https://www.enoticiamojuidoscampos.com.br/", name: "É Noticia Mojuí dos Campos" },
  { url: "https://www.enoticiamontealegre.com.br/", name: "É Noticia Monte Alegre" },
  { url: "https://www.enoticianovatimboteua.com.br/", name: "É Noticia Nova Timboteua" },
  { url: "https://www.enoticiaoeiras.com.br/", name: "É Noticia Oeiras" },
  { url: "https://www.enoticiaoriximina.com.br/", name: "É Noticia Oriximiná" },
  { url: "https://www.enoticiaourilandiadonorte.com.br/", name: "É Noticia Ourilândia do Norte" },
  { url: "https://www.enoticiaparagominas.com.br/", name: "É Noticia Paragominas" },
  { url: "https://www.enoticiaparauapebas.com.br/", name: "É Noticia Parauapebas" },
  { url: "https://www.enoticiapontadepedras.com.br/", name: "É Noticia Ponta de Pedras" },
  { url: "https://www.enoticiaportel.com.br/", name: "É Noticia Portel" },
  { url: "https://www.enoticiaportodemoz.com.br/", name: "É Noticia Porto de Moz" },
  { url: "https://www.enoticiaprainha.com.br/", name: "É Noticia Prainha" },
  { url: "https://www.enoticiasalinas.com.br/", name: "É Noticia Salinas" },
  { url: "https://www.enoticiasalgado.com.br/", name: "É Noticia Salgado" },
  { url: "https://www.enoticiasantarem.com.br/", name: "É Noticia Santarém" },
  { url: "https://www.enoticiasoure.com.br/", name: "É Noticia Soure" },
  { url: "https://www.enoticiatapajos.com.br/", name: "É Noticia Tapajós" },
  { url: "https://www.enoticiatracuateua.com.br/", name: "É Noticia Tracuateua" },
  { url: "https://www.enoticiavitoriadoxingu.com.br/", name: "É Noticia Vitória do Xingu" },
  { url: "https://www.enoticiaxingu.com.br/", name: "É Noticia Xingu" },
  { url: "https://www.enoticiaquatipuru.com.br/", name: "É Noticia Quatipuru" }


  
].sort((a, b) => a.name.localeCompare(b.name));
