export const links = [
  { url: "https://www.enoticiaabaetetuba.com.br/", name: "É Notícia Abaetetuba" },
 { url: "https://www.enoticiaacara.com.br/", name: "É Notícia Acará" },
  { url: "https://www.enoticiaaltamira.com.br/", name: "É Notícia Altamira" },
  { url: "https://www.enoticiaananindeua.com.br/", name: "É Notícia Ananindeua" },
  { url: "https://www.enoticiaaugustocorrea.com.br/", name: "É Notícia Augusto Corrêa" },
  { url: "https://www.enoticiaalmerin.com.br/", name: "É Notícia Almeirim" },
  { url: "https://www.enoticiaaraguaia.com.br/", name: "É Notícia Araguaia" },
  { url: "https://www.enoticiabagre.com.br/", name: "É Notícia Bagre" },
  { url: "https://www.enoticiabaixoamazonas.com.br/", name: "É Notícia Baixo Amazonas" },
  { url: "https://www.enoticiabaixotocantins.com.br/", name: "É Notícia Baixo Tocantins" },
  { url: "https://www.enoticiabarcarena.com.br/", name: "É Notícia Barcarena" },
  { url: "https://www.enoticiabelterra.com.br/", name: "É Notícia Belterra" },
  { url: "https://www.enoticiabelem.com.br/", name: "É Notícia Belém" },
  { url: "https://www.enoticiabenevides.com/", name: "É Notícia Benevides" },
  { url: "https://www.enoticiaboavistense.com.br/", name: "É Notícia Boa Vista" },
  { url: "https://www.enoticiabraganca.com.br/", name: "É Notícia Bragança" },
  { url: "https://www.enoticiacaete.com.br/", name: "É Notícia Caeté" },
  { url: "https://www.enoticiacapanema.com.br/", name: "É Notícia Capanema" },
  { url: "https://www.enoticiacapim.com.br/", name: "É Notícia Capim" },
  { url: "https://www.enoticiacastanhal.com.br/", name: "É Notícia Castanhal" },
  { url: "https://www.enoticiacarajas.com.br/", name: "É Notícia Carajás" },
  { url: "https://www.enoticiacolares.com.br/", name: "É Notícia Colares" },
  { url: "https://www.enoticiaconceicaoaraguaia.com.br/", name: "É Notícia Conceição do Araguaia" },
  { url: "https://www.enoticiacuruca.com.br/", name: "É Notícia Curuçá" },
  { url: "https://www.enoticiadomeliseu.com.br/", name: "É Notícia Dom Eliseu" },
  { url: "https://www.enoticiafaro.com.br/", name: "É Notícia Faro" },
  { url: "https://www.enoticiagarrafaodonorte.com.br/", name: "É Notícia Garrafão do Norte" },
  { url: "https://www.enoticiagoianesia.com.br/", name: "É Notícia Goianésia" },
  { url: "https://www.enoticiaguajarina.com.br/", name: "É Notícia Guajarina" },
  { url: "https://www.enoticiamuana.com.br/", name: "É Notícia Muaná" },
  { url: "https://www.enoticiaitaituba.com.br/", name: "É Notícia Itaituba" },
  { url: "https://www.enoticiaitupiranga.com.br/", name: "É Notícia Itupiranga" },
  { url: "https://www.enoticiajuruti.com.br/", name: "É Notícia Juruti" },
  { url: "https://www.enoticialagodetucurui.com.br/", name: "É Notícia Lago de Tucuruí" },
  { url: "https://www.enoticiamagalhaesbarata.com.br/", name: "É Notícia Magalhães Barata" },
  { url: "https://www.enoticiamaraba.com.br/", name: "É Notícia Marabá" },
  { url: "https://www.enoticiamaracana.com.br/", name: "É Notícia Maracanã" },
  { url: "https://www.enoticiamarajo.com.br/", name: "É Notícia Marajó" },
  { url: "https://www.enoticiamarituba.com.br/", name: "É Notícia Marituba" },
  { url: "https://www.enoticiamojuidoscampos.com.br/", name: "É Notícia Mojuí dos Campos" },
  { url: "https://www.enoticiamontealegre.com.br/", name: "É Notícia Monte Alegre" },
  { url: "https://www.enoticianovatimboteua.com.br/", name: "É Notícia Nova Timboteua" },
  { url: "https://www.enoticiaoeiras.com.br/", name: "É Notícia Oeiras" },
  { url: "https://www.enoticiaoriximina.com.br/", name: "É Notícia Oriximiná" },
  { url: "https://www.enoticiaourilandiadonorte.com.br/", name: "É Notícia Ourilândia do Norte" },
  { url: "https://www.enoticiaparagominas.com.br/", name: "É Notícia Paragominas" },
  { url: "https://www.enoticiaparauapebas.com.br/", name: "É Notícia Parauapebas" },
  { url: "https://www.enoticiapontadepedras.com.br/", name: "É Notícia Ponta de Pedras" },
  { url: "https://www.enoticiaportel.com.br/", name: "É Notícia Portel" },
  { url: "https://www.enoticiaportodemoz.com.br/", name: "É Notícia Porto de Moz" },
  { url: "https://www.enoticiaprainha.com.br/", name: "É Notícia Prainha" },
  { url: "https://www.enoticiasalinas.com.br/", name: "É Notícia Salinas" },
  { url: "https://www.enoticiasalgado.com.br/", name: "É Notícia Salgado" },
  { url: "https://www.enoticiasantarem.com.br/", name: "É Notícia Santarém" },
  { url: "https://www.enoticiasoure.com.br/", name: "É Notícia Soure" },
  { url: "https://www.enoticiatapajos.com.br/", name: "É Notícia Tapajós" },
  { url: "https://www.enoticiatracuateua.com.br/", name: "É Notícia Tracuateua" },
  { url: "https://www.enoticiavitoriadoxingu.com.br/", name: "É Notícia Vitória do Xingu" },
  { url: "https://www.enoticiaxingu.com.br/", name: "É Notícia Xingu" },
  { url: "https://www.enoticiaquatipuru.com.br/", name: "É Notícia Quatipuru" }
  
  

].sort((a, b) => a.name.localeCompare(b.name));



